name: flutter_template
description: fultter template

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_swiper: ^1.0.6
  # https://github.com/alibaba/flutter_boost
  flutter_boost: ^1.12.13
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  #  reflectable:
  #    git: git://github.com/dart-lang/reflectable.git
  meta: ^1.0.4
  #  http: ^0.12.1-dev
  built_collection: '>=2.0.0 <5.0.0'
  built_value: ^7.0.2
  # add this line to your dependencies
  fluttertoast: ^4.0.0
  fenguwxp_fluro:
    git: git://github.com/fengwuxp/fenguwxp_fluro.git
  fengwuxp_dart_declarative_api:
    git: git://github.com/fengwuxp/fengwuxp_dart_declarative_api.git
  fengwuxp_dart_basic:
    git: git://github.com/fengwuxp/fengwuxp_dart_basic.git
  environment_config: ^2.2.2
  bot_toast: ^3.0.0
  flutter_spinkit: ^4.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  #  annotation_route: any
  build_runner: any
  build_test: any
  # If you need to run web tests, you will also need this dependency.
  #  build_web_compilers: any
  built_value_generator: ^7.0.9

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/icons/icon_independent_travel.png
    - assets/images/icons/icon_2.png
    - assets/images/icons/icon_3.png
    - assets/images/icons/icon_4.png
    - assets/images/icons/icon_5.png
    - assets/images/icons/icon_6.png
    - assets/images/icons/icon_7.png
    - assets/images/icons/icon_8.png
    - assets/images/icons/icon_shopping.png
    - assets/images/icons/icon_shopping_active.png
    - assets/images/icons/icon_my.png
    - assets/images/icons/icon_my_active.png
    - assets/images/icons/icon_cart.png
    - assets/images/icons/icon_cart_active.png
    - assets/images/icons/icon_home.png
    - assets/images/icons/icon_home_active.png
    - assets/images/ad.png
    - assets/images/goods_default.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
